# Generated by Django 4.0.6 on 2022-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseovsfenix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matperseo',
            name='enfenix',
        ),
        migrations.AlterField(
            model_name='matperseo',
            name='acta',
            field=models.CharField(default='0', max_length=100, verbose_name='Acta'),
        ),
    ]
