# Generated by Django 4.0.6 on 2022-08-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_epm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('dias_urbano', models.CharField(max_length=50, null=True)),
                ('dias_rural', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Actividad epm',
                'verbose_name_plural': 'Actividades epm',
            },
        ),
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.TextField(default=0, max_length=100, null=True)),
                ('Subped', models.CharField(default=0, max_length=100, null=True)),
                ('Soli', models.CharField(default=0, max_length=200, null=True)),
                ('Producto_id', models.CharField(default=0, max_length=200, null=True)),
                ('Tipo_Trabajo', models.CharField(default=0, max_length=200, null=True)),
                ('Tipo_Elemento_ID', models.CharField(default=0, max_length=200, null=True)),
                ('Fecha_Recibo', models.CharField(default=0, max_length=500)),
                ('Fecha_Ingreso_Sol', models.CharField(default=0, max_length=500)),
                ('Fecha_Concepto', models.CharField(default=0, max_length=500)),
                ('Fecha_Inicio_ANS', models.CharField(default=0, max_length=500)),
                ('Días_ANS', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Estado', models.CharField(default=0, max_length=500, null=True)),
                ('Concepto', models.CharField(default=0, max_length=500, null=True)),
                ('Nombre_concepto', models.CharField(default=0, max_length=500, null=True)),
                ('ClienteID', models.CharField(default=0, max_length=500, null=True)),
                ('Nombre_Cliente', models.CharField(default=0, max_length=500, null=True)),
                ('Telefono', models.CharField(default=0, max_length=100, null=True)),
                ('Correo', models.CharField(default=0, max_length=100, null=True)),
                ('Direccion_Correspondencia', models.CharField(max_length=5000, null=True)),
                ('Municipio_Correspondencia', models.CharField(max_length=5000, null=True)),
                ('Telefono_Contacto', models.CharField(default=0, max_length=5000, null=True)),
                ('Celular_Contacto', models.CharField(default=0, max_length=5000, null=True)),
                ('Direccion', models.CharField(max_length=5000, null=True)),
                ('Municipio', models.CharField(max_length=5000, null=True)),
                ('Instalación', models.CharField(max_length=5000, null=True)),
                ('Area_Operativa', models.CharField(max_length=5000, null=True)),
                ('Subzona', models.CharField(max_length=5000, null=True)),
                ('Area_Trabajo', models.CharField(max_length=5000, null=True)),
                ('Ruta', models.CharField(max_length=5000, null=True)),
                ('Coordenadax', models.CharField(max_length=5000, null=True)),
                ('Coordenaday', models.CharField(max_length=5000, null=True)),
                ('Actividad', models.CharField(max_length=5000, null=True)),
                ('Equipo', models.CharField(max_length=5000, null=True)),
                ('Nombre', models.CharField(max_length=5000, null=True)),
                ('Fecha_Programación', models.CharField(default=0, max_length=5000)),
                ('Num_Proyecto', models.CharField(max_length=500, null=True)),
                ('Tipo_Dirección', models.CharField(max_length=10000, null=True)),
                ('Observación', models.CharField(max_length=5000, null=True)),
                ('Observación_Solicitud', models.CharField(max_length=5000, null=True)),
                ('Pedido_CRM', models.CharField(default=0, max_length=5000, null=True)),
                ('dias_vencimiento', models.IntegerField(default=0, verbose_name='Dias de vencimiento')),
                ('dias_vencimiento_epm', models.IntegerField(default=0, verbose_name='Dias de vencimiento epm')),
                ('fecha_vencimiento', models.CharField(default=0, max_length=30, verbose_name='Fecha vencimiento')),
                ('encargado', models.CharField(max_length=100, null=True)),
                ('estado_cierre', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_cierre', models.CharField(default=0, max_length=100, null=True)),
                ('fecha_vence_sin_hora', models.CharField(default=0, max_length=50)),
                ('hora_vencimiento', models.CharField(default=0, max_length=50)),
                ('fecha_vence_epm', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'Programador',
                'verbose_name_plural': 'Programador',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Vencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.TextField(default=0, max_length=100)),
                ('Instalación', models.CharField(max_length=5000, null=True)),
                ('Actividad', models.CharField(max_length=5000, null=True)),
                ('Observación', models.CharField(max_length=5000, null=True)),
                ('fecha_vencimiento', models.CharField(default='Sin registro', max_length=30, null=True, verbose_name='Fecha vencimiento')),
                ('encargado', models.CharField(max_length=100, null=True)),
                ('fecha_cierre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vencido',
                'verbose_name_plural': 'Vencidos',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('dias_urbano', models.CharField(max_length=50, null=True)),
                ('dias_rural', models.CharField(max_length=50, null=True)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionvencimientos.encargado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
