# Generated by Django 4.0.6 on 2022-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.TextField(default=0, max_length=100, null=True)),
                ('Subped', models.CharField(default=0, max_length=100, null=True)),
                ('Soli', models.CharField(default=0, max_length=200, null=True)),
                ('Producto_id', models.CharField(default=0, max_length=200, null=True)),
                ('Tipo_Trabajo', models.CharField(default=0, max_length=200, null=True)),
                ('Tipo_Elemento_ID', models.CharField(default=0, max_length=200, null=True)),
                ('Fecha_Recibo', models.CharField(default=0, max_length=500)),
                ('Fecha_Ingreso_Sol', models.CharField(default=0, max_length=500)),
                ('Fecha_Concepto', models.CharField(default=0, max_length=500)),
                ('Fecha_Inicio_ANS', models.CharField(default=0, max_length=500)),
                ('Días_ANS', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Estado', models.CharField(default=0, max_length=500, null=True)),
                ('Concepto', models.CharField(default=0, max_length=500, null=True)),
                ('Nombre_concepto', models.CharField(default=0, max_length=500, null=True)),
                ('ClienteID', models.CharField(default=0, max_length=500, null=True)),
                ('Nombre_Cliente', models.CharField(default=0, max_length=500, null=True)),
                ('Telefono', models.CharField(default=0, max_length=100, null=True)),
                ('Correo', models.CharField(default=0, max_length=100, null=True)),
                ('Direccion_Correspondencia', models.CharField(max_length=5000, null=True)),
                ('Municipio_Correspondencia', models.CharField(max_length=5000, null=True)),
                ('Telefono_Contacto', models.CharField(default=0, max_length=5000, null=True)),
                ('Celular_Contacto', models.CharField(default=0, max_length=5000, null=True)),
                ('Direccion', models.CharField(max_length=5000, null=True)),
                ('Municipio', models.CharField(max_length=5000, null=True)),
                ('Instalación', models.CharField(max_length=5000, null=True)),
                ('Area_Operativa', models.CharField(max_length=5000, null=True)),
                ('Subzona', models.CharField(max_length=5000, null=True)),
                ('Area_Trabajo', models.CharField(max_length=5000, null=True)),
                ('Ruta', models.CharField(max_length=5000, null=True)),
                ('Coordenadax', models.CharField(max_length=5000, null=True)),
                ('Coordenaday', models.CharField(max_length=5000, null=True)),
                ('Actividad', models.CharField(max_length=5000, null=True)),
                ('Equipo', models.CharField(max_length=5000, null=True)),
                ('Nombre', models.CharField(max_length=5000, null=True)),
                ('Fecha_Programación', models.CharField(default=0, max_length=5000)),
                ('Num_Proyecto', models.CharField(max_length=500, null=True)),
                ('Tipo_Dirección', models.CharField(max_length=10000, null=True)),
                ('Observación', models.CharField(max_length=5000, null=True)),
                ('Observación_Solicitud', models.CharField(max_length=5000, null=True)),
                ('Pedido_CRM', models.CharField(default=0, max_length=5000, null=True)),
                ('dias_vencimiento', models.IntegerField(default=0, verbose_name='Dias de vencimiento')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Acta',
                'ordering': ['Actividad'],
            },
        ),
        migrations.CreateModel(
            name='Novedad_acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.TextField(default=0, max_length=100, null=True)),
                ('actividad', models.CharField(max_length=5000, null=True)),
                ('novedad', models.CharField(max_length=5000, null=True)),
                ('estado', models.CharField(default='Aplica', max_length=100)),
            ],
            options={
                'verbose_name': 'Novedades Acta',
                'verbose_name_plural': 'Novedades Acta',
                'ordering': ['actividad'],
            },
        ),
    ]
