# Generated by Django 4.0.6 on 2022-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0003_remove_acta_dias_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={'ordering': ['actividad'], 'verbose_name': 'Acta', 'verbose_name_plural': 'Acta'},
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Actividad',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Area_Operativa',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Area_Trabajo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Celular_Contacto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='ClienteID',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Concepto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Coordenadax',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Coordenaday',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Direccion_Correspondencia',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Días_ANS',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Equipo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Fecha_Concepto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Fecha_Ingreso_Sol',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Fecha_Inicio_ANS',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Fecha_Programación',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Fecha_Recibo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Instalación',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Municipio',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Municipio_Correspondencia',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Nombre_Cliente',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Nombre_concepto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Num_Proyecto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Observación',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Observación_Solicitud',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Pedido',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Pedido_CRM',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Producto_id',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Ruta',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Soli',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Subped',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Subzona',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Telefono_Contacto',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Tipo_Dirección',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Tipo_Elemento_ID',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='Tipo_Trabajo',
        ),
        migrations.AddField(
            model_name='acta',
            name='acta',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='actividad',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='area_operativa',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='cantidad',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='cobro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='contrato',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='descent',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_estado',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='item_cont',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='item_res',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='municipio',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='pagina',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='pedido',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='red_interna',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='ruta',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='subz',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='suminis',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='tipo',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='tipo_item',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='tipo_operacion',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='tipre',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='urbrur',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='valor_costo',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='acta',
            name='vlr_cliente',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='novedad_acta',
            name='pedido',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
