# Generated by Django 4.0.6 on 2022-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0004_alter_acta_options_remove_acta_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad_acta',
            name='item',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='novedad_acta',
            name='pagina',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='novedad_acta',
            name='actividad',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='novedad_acta',
            name='novedad',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='novedad_acta',
            name='pedido',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
