# Generated by Django 4.0.6 on 2022-08-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0006_faltanteperseo_guia_matfenix_matperseo_numeroacta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('codigo_despacho', models.CharField(max_length=100, verbose_name='Código despacho')),
                ('fecha', models.CharField(max_length=500, verbose_name='Fecha')),
                ('encargado', models.CharField(max_length=500, verbose_name='Encargado')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Oficial')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion_acta_epm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=10, verbose_name='Pedido')),
                ('actividad', models.CharField(max_length=500, verbose_name='Actividad')),
                ('item_cont', models.CharField(max_length=100, verbose_name='item_cont')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Liquidación Acta Epm',
                'verbose_name_plural': 'Liquidación Acta Epm',
            },
        ),
        migrations.CreateModel(
            name='Material_utilizado_perseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=10, verbose_name='Pedido')),
                ('instalador', models.CharField(max_length=500, verbose_name='Instalador')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Material Utilizado Perseo',
                'verbose_name_plural': 'Material Utilizado Perseo',
            },
        ),
    ]
