# Generated by Django 4.0.6 on 2022-08-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0007_despacho_ingreso_liquidacion_acta_epm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='nombre',
            new_name='encargado',
        ),
    ]
