# Generated by Django 4.0.6 on 2022-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0008_rename_nombre_ingreso_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_utilizado_perseo',
            name='actividad',
            field=models.CharField(default='0', max_length=500, verbose_name='Actividad'),
        ),
    ]
