# Generated by Django 4.0.6 on 2022-08-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0009_material_utilizado_perseo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion_acta_epm',
            name='conc_pedido_codigo',
            field=models.CharField(default='0', max_length=100, verbose_name='concatenacion'),
        ),
        migrations.AddField(
            model_name='liquidacion_acta_epm',
            name='encargado',
            field=models.CharField(default='0', max_length=100, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='material_utilizado_perseo',
            name='conc_pedido_codigo',
            field=models.CharField(default='0', max_length=100, verbose_name='concatenacion'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='cantidad',
            field=models.CharField(default='0', max_length=100, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='encargado',
            field=models.CharField(default='0', max_length=500, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='material_utilizado_perseo',
            name='cantidad',
            field=models.CharField(default='0', max_length=100, verbose_name='Cantidad'),
        ),
    ]
