# Generated by Django 4.0.6 on 2022-08-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0011_oficial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingreso',
            new_name='Inicio',
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Inicio', 'verbose_name_plural': 'Inicio'},
        ),
    ]
