# Generated by Django 4.0.6 on 2022-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0012_rename_ingreso_inicio_alter_inicio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_A_Buscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='--', max_length=500, verbose_name='Oficial')),
            ],
            options={
                'verbose_name': 'Material a buscar',
                'verbose_name_plural': 'Material a buscar',
            },
        ),
    ]
