# Generated by Django 4.0.6 on 2022-08-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0013_material_a_buscar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0', max_length=100, verbose_name='Código')),
                ('inicio', models.CharField(default='0', max_length=100, verbose_name='Código')),
                ('despachado', models.CharField(default='0', max_length=100, verbose_name='Código')),
                ('epm', models.CharField(default='0', max_length=100, verbose_name='Código')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionvencimientos.oficial')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
