# Generated by Django 4.0.6 on 2022-08-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0014_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='diferencia',
            field=models.CharField(default='0', max_length=100, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='despachado',
            field=models.CharField(default='0', max_length=100, verbose_name='Despachado'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='epm',
            field=models.CharField(default='0', max_length=100, verbose_name='Epm'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='inicio',
            field=models.CharField(default='0', max_length=100, verbose_name='Inicio'),
        ),
    ]
