# Generated by Django 4.0.6 on 2022-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0016_alter_stock_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('fecha', models.CharField(max_length=500, verbose_name='Fecha')),
                ('encargado', models.CharField(default='0', max_length=500, verbose_name='Encargado')),
                ('cantidad', models.CharField(default='0', max_length=100, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Reintegro oficial',
                'verbose_name_plural': 'Reintegros oficiales',
            },
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'verbose_name': 'Despacho oficial', 'verbose_name_plural': 'Despachos oficiales'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Cantidadi Inicio Oficial', 'verbose_name_plural': 'Cantidadi Inicio Oficial'},
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='codigo_despacho',
        ),
    ]
