# Generated by Django 4.0.6 on 2022-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0017_reintegro_alter_despacho_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reintegrado',
            field=models.CharField(default='0', max_length=100, verbose_name='Reintegrado'),
        ),
    ]
