# Generated by Django 4.0.6 on 2022-09-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0018_stock_reintegrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acta',
        ),
        migrations.DeleteModel(
            name='Novedad_acta',
        ),
    ]
