# Generated by Django 4.0.6 on 2022-09-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0019_delete_acta_delete_novedad_acta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faltanteperseo',
        ),
        migrations.DeleteModel(
            name='Guia',
        ),
        migrations.DeleteModel(
            name='matfenix',
        ),
        migrations.DeleteModel(
            name='matperseo',
        ),
        migrations.DeleteModel(
            name='NumeroActa',
        ),
    ]
