# Generated by Django 4.0.6 on 2022-09-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0021_faltanteperseo_guia_matfenix_matperseo_numeroacta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Inicio',
        ),
        migrations.DeleteModel(
            name='Liquidacion_acta_epm',
        ),
        migrations.DeleteModel(
            name='Material_A_Buscar',
        ),
        migrations.DeleteModel(
            name='Material_utilizado_perseo',
        ),
        migrations.DeleteModel(
            name='Oficial',
        ),
        migrations.DeleteModel(
            name='Reintegro',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
