# Generated by Django 4.0.6 on 2022-11-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionvencimientos', '0022_delete_despacho_delete_inicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faltanteperseo',
        ),
        migrations.DeleteModel(
            name='matfenix',
        ),
        migrations.DeleteModel(
            name='matperseo',
        ),
    ]
