# Generated by Django 4.0.6 on 2022-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analisis_acta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad_acta',
            name='municipio',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='novedad_acta',
            name='tipre',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
